import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import NavBar from "@/components/headers/NavBar";
import Footer from "@/components/Footer/Footer";
import { Session } from "./session";
import Providers from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <Providers>
      <Session>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
          > <NavBar />
            <Toaster richColors position="top-right" />
            <main className="min-h-[100vh] w-full overflow-x-auto scrollbar-hide">
              {children}
            </main>
            <Footer />
          </body>
      </Session>
     </Providers>
    </html>
  );
}
